version: '3.9'

services:
  api1: &api
    build: .
    container_name: rinha-api-1
    command: "./bin/rails server"
    environment:
      - RUBY_YJIT_ENABLE=1
      - RAILS_ENV=production
      - POSTGRES_HOST=db
      - POSTGRES_DB=rinha_production
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - RAILS_MASTER_KEY=ea6fbedaed66c1a5f03fc58b03a1ca29
    depends_on:
      - db
    ports:
      - "3000"
    deploy:
      resources:
        limits:
          cpus: '0.45'
          memory: '0.5GB'
  api2:
    <<: *api
    container_name: rinha-api-2
    entrypoint: "/rails/docker-entrypoint-2"

  db:
    image: postgres:14.2-alpine
    command:
      "postgres -c 'max_connections=500'"
    environment:
      - POSTGRES_DB=rinha_production
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '1.7GB'

  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 9999:9999
    depends_on:
      - api1
      - api2
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '0.3GB'
