#!/bin/bash
sleep 5 # waiting postgres
# If running the rails server then create or migrate existing database
if [ "${*}" == "./bin/rails server" ]; then
  DISABLE_DATABASE_ENVIRONMENT_CHECK=1 ./bin/rails db:reset db:create db:migrate
fi

exec "${@}"
