
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("POSTGRES_HOST") { 'localhost' } %>
  port: 5432

development:
  <<: *default
  database: rinha_backend_2023_development

test:
  <<: *default
  database: rinha_backend_2023_test

production:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB") { 'rinha_production' } %>
  username: <%= ENV.fetch("POSTGRES_USER") { 'postgres' } %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") { 'password' } %>
